spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/shedlock  # MySQL 서버 주소와 데이터베이스 이름
    username: root                             # MySQL 사용자 이름
    password: 1234                             # MySQL 사용자 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10                    # 커넥션 풀 최대 크기

  jpa:
    show-sql: true                             # SQL 쿼리 로그를 콘솔에 출력
    hibernate:
      ddl-auto: none                    # 애플리케이션 시작 시 테이블 생성, 종료 시 삭제
    properties:
      hibernate:
        format_sql: true                       # 포맷된 형식으로 SQL 쿼리 출력
        use_sql_comments: true                 # 쿼리 주석 출력
        generate_statistics: true              # 쿼리 통계 정보 출력
    open-in-view: false

  h2:
    console:
      enabled: true                            # H2 콘솔 사용 가능

server:
  port: 8081                                   # 서버 포트 번호

logging:
  level:
    org.hibernate.SQL: debug # logger에 출력하려면
    org.hibernate.type.descriptor.sql: trace # 파라미터 값 출력



