spring:
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
#        show_sql: 'true'
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;NON_KEYWORDS=USER
    username: sa
    password:

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE