spring:
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
#        show_sql: 'true'
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/concurrency
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 100

#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test;NON_KEYWORDS=USER
#    username: sa
#    password:

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE

logging:
  level:
    org.springframework.kafka.*: OFF
    org.springframework.kafka.listener.[KafkaMessageListenerContainer$ListenerConsumer]: OFF
    org.apache.kafka.*: OFF
    kafka.*: OFF
    org.apache.zookeeper.*: OFF